"""Add clock_in_time and clock_out_time to Attendance

Revision ID: 535e3ff1b4fd
Revises: 2ae2bd5a1ad3
Create Date: 2025-04-30 09:09:41.739577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535e3ff1b4fd'
down_revision = '2ae2bd5a1ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('clock_out_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('surname',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('clock_out_time')
        batch_op.drop_column('clock_in_time')

    # ### end Alembic commands ###
